#!/bin/bash

# Description: Self-contained Liquibase wrapper to update the database effortless
# Author: sodep S.A.

# Core parameters
LIQUIBASE=liquibase-3.1.1-bin
INGRES_ZIP=iijdbc-10.0.x-v4.0.7.zip
INGRES_JAR=iijdbc.jar
BASE_DIR=db

TEMP_DIR=${BASE_DIR}/temp
CONF_DIR=${BASE_DIR}/conf

# Move inside the script's directory if required
INITIAL_DIR=`dirname $0`
if [ "$INITIAL_DIR" == '.' ]; then
    [ -n "$VERBOSE" ] && echo "I: Changing un dir up"
    cd ..
fi

# synthesized parameters
LIQUIBASE_URL=http://downloads.sourceforge.net/project/liquibase/Liquibase%20Core/${LIQUIBASE}.tar.gz
INGRES_URL=http://esdftp.actian.com/~hknstY/${INGRES_ZIP}

LIQUIBASE_DIR=${TEMP_DIR}/${LIQUIBASE}
LIQUIBASE_BIN=${LIQUIBASE_DIR}/liquibase
LIQUIBASE_CONF=${CONF_DIR}/liquibase.properties
LIQUIBASE_CHANGELOG=${CONF_DIR}/changelog.xml

INGRES_PATH=${TEMP_DIR}/$INGRES_ZIP

# Check Liquibase properties file existence
[ ! -f $LIQUIBASE_CONF ] && echo "ERROR: Liquibase configuration file not found at: $LIQUIBASE_CONF" && exit 2

# Check Liquibase changelog file existence
#[ ! -f $LIQUIBASE_CHANGELOG ] && echo "ERROR: Liquibase changelog file not found at: $LIQUIBASE_CHANGELOG" && exit 2

# Check that at least one parameter is provided
[ $# -lt 1 ] && echo "ERROR: No parameter specified" && exit 3

# Check that liquibase is in the PATH to be able to run
if [ ! -f $LIQUIBASE_BIN ]; then
    wget -c $LIQUIBASE_URL -P $TEMP_DIR
    _RET=$?
    if [ "$_RET" -ne 0 ]; then
	echo "ERROR: Could not download Liquibase. Do it manually and run again this script (wget -c $LIQUIBASE_URL -P $TEMP_DIR)"
	exit 4
    fi
    mkdir -p $LIQUIBASE_DIR
    tar xzf ${TEMP_DIR}/${LIQUIBASE}.tar.gz -C $LIQUIBASE_DIR
    chmod +x $LIQUIBASE_BIN
fi

if [ ! -f $INGRES_PATH ]; then
    type wget >/dev/null 2>&1 || { echo >&2 "ERROR: I require wget but it's not installed. Aborting."; exit 1; }
    wget -c $INGRES_URL -P $TEMP_DIR
    _RET=$?
    if [ "$_RET" -ne 0 ]; then
        echo "ERROR: Could not download ${INGRES_ZIP}. Do it manually and run again this script (wget -c $INGRES_URL -P $TEMP_DIR)"
        exit 4
    else
        cd $TEMP_DIR
        unzip -q $INGRES_PATH
        INGRES_JAR=$TEMP_DIR/$INGRES_JAR
    fi
fi

# run liquibase
$LIQUIBASE_BIN --classpath=$INGRES_JAR --changeLogFile=$LIQUIBASE_CHANGELOG --defaultsFile=$LIQUIBASE_CONF --logLevel=info $@
