#!/bin/bash -e

[ -z "${ENV_VARS}" ] && echo "ERROR: No environment variable ENV_VARS defined. Aborting" && exit 1
[ ! -f "${ENV_VARS}" ] && echo "ERROR: The ENV_VARS does not exist or is not a file. Aborting." && exit 1
type mvn >/dev/null 2>&1 || { echo >&2 "ERROR: I require 'mvn' but it's not installed. Aborting."; exit 1; }

source ${ENV_VARS}

[ -z "$LOG4J_FILE" ] && echo "ERROR: LOG4J_FILE not defined in ${ENV_VARS}. Aborting" && exit 1
[ -z "$PROFILE_DIR" ] && echo "ERROR: PROFILE_DIR not defined in ${ENV_VARS}. Aborting" && exit 1

[ $# -eq 0 ] && echo "ERROR: No parameter provided" && exit 2


function seed_db
{
    scripts/lib/seed-db
}

function liquibase_update {
    scripts/lib/liquibase-update
}

function drop_and_create_db
{
    scripts/lib/drop-create-db
}

function show_help
{
    echo "The following options are:"
    echo "    update: Update liquibase"
    echo "    fresh: Drop and create DB, liquibase, seed"
    echo "    schema: Drop and create DB, liquibase"
    echo "    seed: Just run the seed-date.sql script. This will clean the DB and add initial fake but working data"
    echo "    help: Show this help"
}

case "$1" in
    'update')
	liquibase_update
	;;
    'schema')
	drop_and_create_db
	liquibase_update
	;;
    'fresh')
	drop_and_create_db
	liquibase_update
	seed_db
	;;
    'seed')
	seed_db
	;;
    'help')
	show_help
	;;
    '*')
	echo "ERROR: Unknown parameter $1"
	show_help
	exit 2
	;;
esac

